### ISSUE TITLE
How would one backup more than one Db in mongo

### ISSUE THREAD

**Issue by DoctorOgg** [backup/backup-features#37]
It appears from the documentation that its the mongo backup configuration is only for one DB at a time,  we use 100's of DB's with lots of collections, and we would like to backup all DB's in a replica set using a user in the admin DB. Is this supported today? or is this a new feature?

**Comment by tombruijn** [comment]
Hi @neallawson, backup uses mongodump to backup databases. If mongodump supports it, backup supports it. If mongodump doesn't support it you can always loop over the databases to make more entries for db backups

``` ruby
Model.new(:my_backup, 'My Backup') do
  ["db1", "db2"].each do |dbname|
    database MongoDB do |db|
      db.name = dbname
    end
  end
end
```

**Comment by DoctorOgg** [comment]
I should have made the question more clear, I'm sure the above method would work when your databases are static, however i get to support dev's who will create databases at will, and i would prefer not alter the backup config for each time this happens, the backup script should be able to ask mongo what databases there are, and the proceed to back those up.

**Comment by tombruijn** [comment]
Backup has no method of getting a list of databases. But you could write a small script for it. That's the advantage of using ruby for configuration.

Shell out to mongodb, list the databases, parse them in an array and loop over that array in that model.

I don't think it's the responsibility of the Backup gem to index a list of databases of a machine to be able to backup them all.

**Comment by DoctorOgg** [comment]
would be a really nice feature to have, since most other database backups assume you want to backup the entire thing, not just one DB, i do feel it would be a great addition to your already great scripts.

**Comment by DoctorOgg** [comment]
think of it this way, do you specify each and every file to backup on a file system?, in most cases no... in the someway DB's should be given the same treatment.

**Comment by tombruijn** [comment]
I looked into mongodump just now, since I haven't used it in 3 years now, but it looks like it supports multiple database.

From the documentation: https://docs.mongodb.org/manual/reference/program/mongodump/#cmdoption--db

```
--db <database>, -d <database>
  Specifies a database to backup. If you do not specify a database, mongodump copies all databases in this instance into the dump files.
```

Backup even ignores the name option if it's not set https://github.com/backup/backup/blob/0c7eb22c7b5b8e3f67e0974836eecc9a99a95276/lib/backup/database/mongodb.rb#L128

Please try it without setting the name, it should backup all the database on your db instance without any other effort. I don't know exactly what the result will be, it looks like it will make a dump file per database, but that's what we get from mongodump.

Now if you want to be able to filter the dbs selected, I'm afraid you'll have to resort to my previous suggestion or set up a database server specifically to host the databases you want to backup this way.

Let me know if you have any other questions.
